// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjydykqmcaksbxlxolij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqeWR5a3FtY2Frc2J4bHhvbGlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDQwNzMsImV4cCI6MjA2NzIyMDA3M30.r5ObH1n8EBmw_7KqGWNW1IP5lFziI2a3Qpta59iAbDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});